// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show Firebase, FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
    
import 'firebase_options.dart';


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
Future<void> initializedFirebase() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq0yRlxczuPChtZI7TapHtb4BxejvkGKE',
    appId: '1:831403561285:web:43fb0d5ca556d97d93ae2c',
    messagingSenderId: '831403561285',
    projectId: 'rpl3b-4cf14',
    authDomain: 'rpl3b-4cf14.firebaseapp.com',
    storageBucket: 'rpl3b-4cf14.appspot.com',
    measurementId: 'G-4D6N1FR3CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtkpvMZPUtMTqlvvP3itPbOTE2jJkKRO4',
    appId: '1:831403561285:android:816f605b6bed207893ae2c',
    messagingSenderId: '831403561285',
    projectId: 'rpl3b-4cf14',
    storageBucket: 'rpl3b-4cf14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBWSnhfb3Eokg8DofnBiXUdf9gKFUhnUc',
    appId: '1:831403561285:ios:8af04dfc3e44a25e93ae2c',
    messagingSenderId: '831403561285',
    projectId: 'rpl3b-4cf14',
    storageBucket: 'rpl3b-4cf14.appspot.com',
    iosBundleId: 'com.example.mapsFlutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBWSnhfb3Eokg8DofnBiXUdf9gKFUhnUc',
    appId: '1:831403561285:ios:8af04dfc3e44a25e93ae2c',
    messagingSenderId: '831403561285',
    projectId: 'rpl3b-4cf14',
    storageBucket: 'rpl3b-4cf14.appspot.com',
    iosBundleId: 'com.example.mapsFlutter1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq0yRlxczuPChtZI7TapHtb4BxejvkGKE',
    appId: '1:831403561285:web:70107a139f8d09d193ae2c',
    messagingSenderId: '831403561285',
    projectId: 'rpl3b-4cf14',
    authDomain: 'rpl3b-4cf14.firebaseapp.com',
    storageBucket: 'rpl3b-4cf14.appspot.com',
    measurementId: 'G-GNVFSKR9W8',
  );
}
